
package br.com.cds.connecta.framework.connector.obiee;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ConditionServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v6")
public interface ConditionServiceSoap {


    /**
     * 
     * @param sessionID
     * @param path
     * @param reportCustomizationParameters
     * @return
     *     returns boolean
     */
    @WebMethod(action = "#evaluateCondition")
    @WebResult(name = "conditionIsTrue", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "evaluateCondition", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.EvaluateCondition")
    @ResponseWrapper(localName = "evaluateConditionResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.EvaluateConditionResult")
    public boolean evaluateCondition(
        @WebParam(name = "path", targetNamespace = "urn://oracle.bi.webservices/v6")
        String path,
        @WebParam(name = "reportCustomizationParameters", targetNamespace = "urn://oracle.bi.webservices/v6")
        List<String> reportCustomizationParameters,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param conditionXML
     * @param reportCustomizationParameters
     * @return
     *     returns boolean
     */
    @WebMethod(action = "#evaluateInlineCondition")
    @WebResult(name = "conditionIsTrue", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "evaluateInlineCondition", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.EvaluateInlineCondition")
    @ResponseWrapper(localName = "evaluateInlineConditionResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.EvaluateInlineConditionResult")
    public boolean evaluateInlineCondition(
        @WebParam(name = "conditionXML", targetNamespace = "urn://oracle.bi.webservices/v6")
        String conditionXML,
        @WebParam(name = "reportCustomizationParameters", targetNamespace = "urn://oracle.bi.webservices/v6")
        List<String> reportCustomizationParameters,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param path
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "#getConditionCustomizableReportElements")
    @WebResult(name = "customizableElement", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getConditionCustomizableReportElements", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetConditionCustomizableReportElements")
    @ResponseWrapper(localName = "getConditionCustomizableReportElementsResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetConditionCustomizableReportElementsResult")
    public List<String> getConditionCustomizableReportElements(
        @WebParam(name = "path", targetNamespace = "urn://oracle.bi.webservices/v6")
        String path,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

}
