
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ReportEditingService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class ReportEditingService
    extends Service
{

    private final static URL REPORTEDITINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPORTEDITINGSERVICE_EXCEPTION;
    private final static QName REPORTEDITINGSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "ReportEditingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTEDITINGSERVICE_WSDL_LOCATION = url;
        REPORTEDITINGSERVICE_EXCEPTION = e;
    }

    public ReportEditingService() {
        super(__getWsdlLocation(), REPORTEDITINGSERVICE_QNAME);
    }
    
    public ReportEditingService(URL wsdlLocation) {
        super(wsdlLocation, REPORTEDITINGSERVICE_QNAME);
    }

    public ReportEditingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ReportEditingServiceSoap
     */
    @WebEndpoint(name = "ReportEditingServiceSoap")
    public ReportEditingServiceSoap getReportEditingServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "ReportEditingServiceSoap"), ReportEditingServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (REPORTEDITINGSERVICE_EXCEPTION!= null) {
            throw REPORTEDITINGSERVICE_EXCEPTION;
        }
        return REPORTEDITINGSERVICE_WSDL_LOCATION;
    }

}
