---
engines:
# rubocop:
#   exclude_paths:
#     - config/engines.yml
# duplication:
#   exclude_paths:
#     - config/engines.yml
# metrics:
#   exclude_paths:
#     - config/engines.yml
# coverage:
#   exclude_paths:
#     - config/engines.yml
exclude_paths:
  - src/test/
