language: java
jdk:
  - oraclejdk8
group: stable
dist: precise
os: linux

cache:
  directories:
    - $HOME/.m2/repository
install:
  - mvn install:install-file -Dfile=connecta-connectors/lib/ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0.2 -Dpackaging=jar
after_success:
  - mvn clean test jacoco:report coveralls:report
  - mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
