
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "HtmlViewService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class HtmlViewService
    extends Service
{

    private final static URL HTMLVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException HTMLVIEWSERVICE_EXCEPTION;
    private final static QName HTMLVIEWSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "HtmlViewService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HTMLVIEWSERVICE_WSDL_LOCATION = url;
        HTMLVIEWSERVICE_EXCEPTION = e;
    }

    public HtmlViewService() {
        super(__getWsdlLocation(), HTMLVIEWSERVICE_QNAME);
    }

    public HtmlViewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns HtmlViewServiceSoap
     */
    @WebEndpoint(name = "HtmlViewService")
    public HtmlViewServiceSoap getHtmlViewService() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "HtmlViewService"), HtmlViewServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (HTMLVIEWSERVICE_EXCEPTION!= null) {
            throw HTMLVIEWSERVICE_EXCEPTION;
        }
        return HTMLVIEWSERVICE_WSDL_LOCATION;
    }

}
