
package br.com.cds.connecta.framework.connector.obiee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HtmlViewServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v6")
public interface HtmlViewServiceSoap {


    /**
     * 
     * @param sessionID
     * @param options
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#startPage")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "startPage", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.StartPage")
    @ResponseWrapper(localName = "startPageResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.StartPageResult")
    public String startPage(
        @WebParam(name = "options", targetNamespace = "urn://oracle.bi.webservices/v6")
        StartPageParams options,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param pageID
     */
    @WebMethod(action = "#endPage")
    @RequestWrapper(localName = "endPage", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.EndPage")
    @ResponseWrapper(localName = "endPageResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.EndPageResult")
    public void endPage(
        @WebParam(name = "pageID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String pageID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param pageID
     * @param report
     * @param reportViewName
     * @param options
     * @param reportParams
     * @param reportID
     */
    @WebMethod(action = "#addReportToPage")
    @RequestWrapper(localName = "addReportToPage", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.AddReportToPage")
    @ResponseWrapper(localName = "addReportToPageResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.AddReportToPageResult")
    public void addReportToPage(
        @WebParam(name = "pageID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String pageID,
        @WebParam(name = "reportID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String reportID,
        @WebParam(name = "report", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportRef report,
        @WebParam(name = "reportViewName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String reportViewName,
        @WebParam(name = "reportParams", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportParams reportParams,
        @WebParam(name = "options", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportHTMLOptions options,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param pageID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#getHeadersHtml")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getHeadersHtml", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetHeadersHtml")
    @ResponseWrapper(localName = "getHeadersHtmlResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetHeadersHtmlResult")
    public String getHeadersHtml(
        @WebParam(name = "pageID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String pageID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param pageID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#getCommonBodyHtml")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getCommonBodyHtml", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetCommonBodyHtml")
    @ResponseWrapper(localName = "getCommonBodyHtmlResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetCommonBodyHtmlResult")
    public String getCommonBodyHtml(
        @WebParam(name = "pageID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String pageID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param pageReportID
     * @param pageID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#getHtmlForReport")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getHtmlForReport", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetHtmlForReport")
    @ResponseWrapper(localName = "getHtmlForReportResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetHtmlForReportResult")
    public String getHtmlForReport(
        @WebParam(name = "pageID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String pageID,
        @WebParam(name = "pageReportID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String pageReportID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param bridge
     */
    @WebMethod(action = "#setBridge")
    @RequestWrapper(localName = "setBridge", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.SetBridge")
    @ResponseWrapper(localName = "setBridgeResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.SetBridgeResult")
    public void setBridge(
        @WebParam(name = "bridge", targetNamespace = "urn://oracle.bi.webservices/v6")
        String bridge,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param reportOptions
     * @param sessionID
     * @param report
     * @param reportViewName
     * @param pageParams
     * @param reportParams
     * @param reportID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#getHtmlForPageWithOneReport")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getHtmlForPageWithOneReport", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetHtmlForPageWithOneReport")
    @ResponseWrapper(localName = "getHtmlForPageWithOneReportResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetHtmlForPageWithOneReportResult")
    public String getHtmlForPageWithOneReport(
        @WebParam(name = "reportID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String reportID,
        @WebParam(name = "report", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportRef report,
        @WebParam(name = "reportViewName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String reportViewName,
        @WebParam(name = "reportParams", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportParams reportParams,
        @WebParam(name = "reportOptions", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportHTMLOptions reportOptions,
        @WebParam(name = "pageParams", targetNamespace = "urn://oracle.bi.webservices/v6")
        StartPageParams pageParams,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

}
