
package br.com.cds.connecta.framework.connector.obiee;

import br.com.cds.connecta.framework.connector.obiee.AuthResult;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SAWSessionServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v6")
public interface SAWSessionServiceSoap {


    /**
     * 
     * @param name
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#logon")
    @WebResult(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "logon", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.Logon")
    @ResponseWrapper(localName = "logonResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.LogonResult")
    public String logon(
        @WebParam(name = "name", targetNamespace = "urn://oracle.bi.webservices/v6")
        String name,
        @WebParam(name = "password", targetNamespace = "urn://oracle.bi.webservices/v6")
        String password);

    /**
     * 
     * @param sessionparams
     * @param name
     * @param password
     * @return
     *     returns oracle.bi.web.soap.AuthResult
     */
    @WebMethod(action = "#logonex")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "logonex", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.Logonex")
    @ResponseWrapper(localName = "logonexResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.LogonexResult")
    public AuthResult logonex(
        @WebParam(name = "name", targetNamespace = "urn://oracle.bi.webservices/v6")
        String name,
        @WebParam(name = "password", targetNamespace = "urn://oracle.bi.webservices/v6")
        String password,
        @WebParam(name = "sessionparams", targetNamespace = "urn://oracle.bi.webservices/v6")
        SAWSessionParameters sessionparams);

    /**
     * 
     * @param sessionID
     */
    @WebMethod(action = "#logoff")
    @RequestWrapper(localName = "logoff", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.Logoff")
    @ResponseWrapper(localName = "logoffResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.LogoffResult")
    public void logoff(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     */
    @WebMethod(action = "#keepAlive")
    @RequestWrapper(localName = "keepAlive", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.KeepAlive")
    @ResponseWrapper(localName = "keepAliveResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.KeepAliveResult")
    public void keepAlive(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        List<String> sessionID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#getCurUser")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getCurUser", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetCurUser")
    @ResponseWrapper(localName = "getCurUserResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetCurUserResult")
    public String getCurUser(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.SessionEnvironment
     */
    @WebMethod(action = "#getSessionEnvironment")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getSessionEnvironment", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetSessionEnvironment")
    @ResponseWrapper(localName = "getSessionEnvironmentResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetSessionEnvironmentResult")
    public SessionEnvironment getSessionEnvironment(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     *            Returns values of BIEE variables associated with the current session
     *            Here is the list of predefined variables :
     *            NQ_SESSION.USER,
     *            NQ_SESSION.USERGUID,
     *            NQ_SESSION.GROUP,
     *            NQ_SESSION.GROUPGUIDS,
     *            NQ_SESSION.WEBGROUPS,
     *            NQ_SESSION.REALM,
     *            NQ_SESSION.REALMGUID,
     *            NQ_SESSION.TOKENS,
     *            NQ_SESSION.REQUESTKEY,
     *            NQ_SESSION.PORTALPATH,
     *            NQ_SESSION.DISPLAYNAME,
     *            NQ_SESSION.SKIN,
     *            NQ_SESSION.STYLE,
     *            NQ_SESSION.EMAIL,
     *            NQ_SESSION.CURRENCYTAG,
     *            NQ_SESSION.ACTUATEUSERID,
     *            NQ_SESSION.TIMEZONE,
     *            NQ_SESSION.DATA_TZ,
     *            NQ_SESSION.DATA_DISPLAY_TZ,
     *            NQ_SESSION.PROXYLEVEL,
     *            NQ_SESSION.USERLOCALE,
     *            NQ_SESSION.USERLANG,
     *            NQ_SESSION.PREFERRED_CURRENCY
     *         
     * 
     * @param sessionID
     * @param names
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "#getSessionVariables")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getSessionVariables", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetSessionVariables")
    @ResponseWrapper(localName = "getSessionVariablesResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetSessionVariablesResult")
    public List<String> getSessionVariables(
        @WebParam(name = "names", targetNamespace = "urn://oracle.bi.webservices/v6")
        List<String> names,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param impersonateID
     * @param name
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#impersonate")
    @WebResult(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "impersonate", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.Impersonate")
    @ResponseWrapper(localName = "impersonateResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ImpersonateResult")
    public String impersonate(
        @WebParam(name = "name", targetNamespace = "urn://oracle.bi.webservices/v6")
        String name,
        @WebParam(name = "password", targetNamespace = "urn://oracle.bi.webservices/v6")
        String password,
        @WebParam(name = "impersonateID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String impersonateID);

    /**
     * 
     * @param impersonateID
     * @param sessionparams
     * @param name
     * @param password
     * @return
     *     returns oracle.bi.web.soap.AuthResult
     */
    @WebMethod(action = "#impersonateex")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "impersonateex", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.Impersonateex")
    @ResponseWrapper(localName = "impersonateexResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ImpersonateexResult")
    public AuthResult impersonateex(
        @WebParam(name = "name", targetNamespace = "urn://oracle.bi.webservices/v6")
        String name,
        @WebParam(name = "password", targetNamespace = "urn://oracle.bi.webservices/v6")
        String password,
        @WebParam(name = "impersonateID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String impersonateID,
        @WebParam(name = "sessionparams", targetNamespace = "urn://oracle.bi.webservices/v6")
        SAWSessionParameters sessionparams);

}
