
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WebCatalogService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class WebCatalogService
    extends Service
{

    private final static URL WEBCATALOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBCATALOGSERVICE_EXCEPTION;
    private final static QName WEBCATALOGSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "WebCatalogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBCATALOGSERVICE_WSDL_LOCATION = url;
        WEBCATALOGSERVICE_EXCEPTION = e;
    }

    public WebCatalogService() {
        super(__getWsdlLocation(), WEBCATALOGSERVICE_QNAME);
    }

    public WebCatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public WebCatalogService(URL wsdlLocation) {
        super(wsdlLocation,WEBCATALOGSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns WebCatalogServiceSoap
     */
    @WebEndpoint(name = "WebCatalogServiceSoap")
    public WebCatalogServiceSoap getWebCatalogServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "WebCatalogServiceSoap"), WebCatalogServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (WEBCATALOGSERVICE_EXCEPTION!= null) {
            throw WEBCATALOGSERVICE_EXCEPTION;
        }
        return WEBCATALOGSERVICE_WSDL_LOCATION;
    }

}
