
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "XmlViewService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class XmlViewService
    extends Service
{

    private final static URL XMLVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException XMLVIEWSERVICE_EXCEPTION;
    private final static QName XMLVIEWSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "XmlViewService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XMLVIEWSERVICE_WSDL_LOCATION = url;
        XMLVIEWSERVICE_EXCEPTION = e;
    }

    public XmlViewService() {
        super(__getWsdlLocation(), XMLVIEWSERVICE_QNAME);
    }

    public XmlViewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public XmlViewService(URL wsdlLocation) {
        super(wsdlLocation, XMLVIEWSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns XmlViewServiceSoap
     */
    @WebEndpoint(name = "XmlViewServiceSoap")
    public XmlViewServiceSoap getXmlViewServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "XmlViewServiceSoap"), XmlViewServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (XMLVIEWSERVICE_EXCEPTION!= null) {
            throw XMLVIEWSERVICE_EXCEPTION;
        }
        return XMLVIEWSERVICE_WSDL_LOCATION;
    }

}
