
package br.com.cds.connecta.framework.connector.obiee;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "XmlViewServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v6")
public interface XmlViewServiceSoap {


    /**
     * 
     * @param executionOptions
     * @param sessionID
     * @param outputFormat
     * @param report
     * @param reportParams
     * @return
     *     returns oracle.bi.web.soap.QueryResults
     */
    @WebMethod(action = "#executeXMLQuery")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "executeXMLQuery", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ExecuteXMLQuery")
    @ResponseWrapper(localName = "executeXMLQueryResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ExecuteXMLQueryResult")
    public QueryResults executeXMLQuery(
        @WebParam(name = "report", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportRef report,
        @WebParam(name = "outputFormat", targetNamespace = "urn://oracle.bi.webservices/v6")
        XMLQueryOutputFormat outputFormat,
        @WebParam(name = "executionOptions", targetNamespace = "urn://oracle.bi.webservices/v6")
        XMLQueryExecutionOptions executionOptions,
        @WebParam(name = "reportParams", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportParams reportParams,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#upgradeXML")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "upgradeXML", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.UpgradeXML")
    @ResponseWrapper(localName = "upgradeXMLResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.UpgradeXMLResult")
    public String upgradeXML(
        @WebParam(name = "xml", targetNamespace = "urn://oracle.bi.webservices/v6")
        String xml,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param executionOptions
     * @param sessionID
     * @param sql
     * @param outputFormat
     * @return
     *     returns oracle.bi.web.soap.QueryResults
     */
    @WebMethod(action = "#executeSQLQuery")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "executeSQLQuery", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ExecuteSQLQuery")
    @ResponseWrapper(localName = "executeSQLQueryResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ExecuteSQLQueryResult")
    public QueryResults executeSQLQuery(
        @WebParam(name = "sql", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sql,
        @WebParam(name = "outputFormat", targetNamespace = "urn://oracle.bi.webservices/v6")
        XMLQueryOutputFormat outputFormat,
        @WebParam(name = "executionOptions", targetNamespace = "urn://oracle.bi.webservices/v6")
        XMLQueryExecutionOptions executionOptions,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param queryID
     * @return
     *     returns oracle.bi.web.soap.QueryResults
     */
    @WebMethod(action = "#fetchNext")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "fetchNext", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.FetchNext")
    @ResponseWrapper(localName = "fetchNextResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.FetchNextResult")
    public QueryResults fetchNext(
        @WebParam(name = "queryID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String queryID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param queryID
     */
    @WebMethod(action = "#cancelQuery")
    @RequestWrapper(localName = "cancelQuery", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.CancelQuery")
    @ResponseWrapper(localName = "cancelQueryResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.CancelQueryResult")
    public void cancelQuery(
        @WebParam(name = "queryID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String queryID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param report
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "#getPromptedFilters")
    @WebResult(name = "promptedFilter", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getPromptedFilters", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetPromptedFilters")
    @ResponseWrapper(localName = "getPromptedFiltersResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetPromptedFiltersResult")
    public List<String> getPromptedFilters(
        @WebParam(name = "report", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportRef report,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

}
