
package br.com.cds.connecta.framework.connector.endeca.mdex.conversation._3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import br.com.cds.connecta.framework.connector.endeca.mdex.conversation._3._0.Request;
import br.com.cds.connecta.framework.connector.endeca.mdex.conversation._3._0.Results;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConversationPort", targetNamespace = "http://www.endeca.com/MDEX/conversation/3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.cds.connecta.framework.connector.endeca.mdex.conversation._3._0.ObjectFactory.class,
    br.com.cds.connecta.framework.connector.endeca.mdex.eql_parser.types.ObjectFactory.class
})
public interface ConversationPort {


    /**
     * 
     * @param request
     * @return
     *     returns com.endeca.mdex.conversation._3._0.Results
     * @throws Fault
     */
    @WebMethod(operationName = "Request")
    @WebResult(name = "Results", targetNamespace = "http://www.endeca.com/MDEX/conversation/3/0", partName = "response")
    public Results request(
        @WebParam(name = "Request", targetNamespace = "http://www.endeca.com/MDEX/conversation/3/0", partName = "request")
        Request request)
        throws Fault
    ;

}
