
package br.com.cds.connecta.framework.connector.endeca.mdex.conversation._3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Conversation-style web service for building applications
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Conversation", targetNamespace = "http://www.endeca.com/MDEX/conversation/3", wsdlLocation = "http://192.168.3.50:11001/endeca-server/ws/conversation/cmsp001?wsdl")
public class Conversation
    extends Service
{

    private final static URL CONVERSATION_WSDL_LOCATION;
    private final static WebServiceException CONVERSATION_EXCEPTION;
    private final static QName CONVERSATION_QNAME = new QName("http://www.endeca.com/MDEX/conversation/3", "Conversation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.3.50:11001/endeca-server/ws/conversation/cmsp001?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERSATION_WSDL_LOCATION = url;
        CONVERSATION_EXCEPTION = e;
    }

    public Conversation() {
        super(__getWsdlLocation(), CONVERSATION_QNAME);
    }

    public Conversation(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERSATION_QNAME);
        
    }

    public Conversation(URL wsdlLocation) {
        super(wsdlLocation, CONVERSATION_QNAME);
    }

    public Conversation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERSATION_QNAME);
    }

    public Conversation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Conversation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ConversationPort
     */
    @WebEndpoint(name = "ConversationPort")
    public ConversationPort getConversationPort() {
        return super.getPort(new QName("http://www.endeca.com/MDEX/conversation/3", "ConversationPort"), ConversationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConversationPort
     */
    @WebEndpoint(name = "ConversationPort")
    public ConversationPort getConversationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.endeca.com/MDEX/conversation/3", "ConversationPort"), ConversationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERSATION_EXCEPTION!= null) {
            throw CONVERSATION_EXCEPTION;
        }
        return CONVERSATION_WSDL_LOCATION;
    }

}
