
package br.com.cds.connecta.framework.connector.endeca.mdex.conversation._3;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://www.endeca.com/MDEX/conversation/3/0")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Object faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Fault(String message, Object faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Fault(String message, Object faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: java.lang.Object
     */
    public Object getFaultInfo() {
        return faultInfo;
    }

}
