
package br.com.cds.connecta.framework.connector.endeca.endeca_server.manage._2;
//package com.endeca.endeca_server.manage._2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A web service to provision and manage data domains in Endeca Server.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "manage", targetNamespace = "http://www.endeca.com/endeca-server/manage/2", wsdlLocation = "http://192.168.3.50:11001/endeca-server/ws/manage?wsdl")
public class Manage
    extends Service
{

    private final static URL MANAGE_WSDL_LOCATION;
    private final static WebServiceException MANAGE_EXCEPTION;
    private final static QName MANAGE_QNAME = new QName("http://www.endeca.com/endeca-server/manage/2", "manage");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.3.50:11001/endeca-server/ws/manage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGE_WSDL_LOCATION = url;
        MANAGE_EXCEPTION = e;
    }

    public Manage() {
        super(__getWsdlLocation(), MANAGE_QNAME);
    }

    public Manage(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGE_QNAME);
    }

    public Manage(URL wsdlLocation) {
        super(wsdlLocation, MANAGE_QNAME);
    }

    public Manage(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGE_QNAME);
    }

    public Manage(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Manage(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ManagePort
     */
    @WebEndpoint(name = "managePort")
    public ManagePort getManagePort() {
        return super.getPort(new QName("http://www.endeca.com/endeca-server/manage/2", "managePort"), ManagePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagePort
     */
    @WebEndpoint(name = "managePort")
    public ManagePort getManagePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.endeca.com/endeca-server/manage/2", "managePort"), ManagePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGE_EXCEPTION!= null) {
            throw MANAGE_EXCEPTION;
        }
        return MANAGE_WSDL_LOCATION;
    }

}
