
package br.com.cds.connecta.framework.connector.endeca.endeca_server.manage._2;
//package com.endeca.endeca_server.manage._2;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.types._2._0.BulkLoadInfo;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.types._2._0.DataDomainDetail;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.types._2._0.DataDomainProfile;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.types._2._0.DataDomainStats;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.types._2._0.DgraphVersion;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "managePort", targetNamespace = "http://www.endeca.com/endeca-server/manage/2")
@XmlSeeAlso({
    br.com.cds.connecta.framework.connector.endeca.endeca_server.manage._2._0.ObjectFactory.class,
    br.com.cds.connecta.framework.connector.endeca.endeca_server.types._2._0.ObjectFactory.class
})
public interface ManagePort {


    /**
     * 
     * @return
     *     returns java.util.List<com.endeca.endeca_server.types._2._0.DataDomainProfile>
     * @throws ManageFault
     */
    @WebMethod
    @WebResult(name = "dataDomainProfile", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
    @RequestWrapper(localName = "listDataDomainProfiles", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ListDataDomainProfiles")
    @ResponseWrapper(localName = "listDataDomainProfilesResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ListDataDomainProfilesResponse")
    public List<DataDomainProfile> listDataDomainProfiles()
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @return
     *     returns com.endeca.endeca_server.types._2._0.DataDomainProfile
     * @throws ManageFault
     */
    @WebMethod
    @WebResult(name = "dataDomainProfile", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
    @RequestWrapper(localName = "getDataDomainProfile", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.GetDataDomainProfile")
    @ResponseWrapper(localName = "getDataDomainProfileResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.GetDataDomainProfileResponse")
    public DataDomainProfile getDataDomainProfile(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name)
        throws ManageFault
    ;

    /**
     * 
     * @param enabled
     * @param name
     * @param ddProfileName
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "createDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.CreateDataDomain")
    @ResponseWrapper(localName = "createDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.CreateDataDomainResponse")
    public void createDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name,
        @WebParam(name = "ddProfileName", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String ddProfileName,
        @WebParam(name = "enabled", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        Boolean enabled)
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @param ddProfileName
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "updateDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.UpdateDataDomain")
    @ResponseWrapper(localName = "updateDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.UpdateDataDomainResponse")
    public void updateDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name,
        @WebParam(name = "ddProfileName", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String ddProfileName)
        throws ManageFault
    ;

    /**
     * 
     * @param enabled
     * @param sourceName
     * @param name
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "cloneDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.CloneDataDomain")
    @ResponseWrapper(localName = "cloneDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.CloneDataDomainResponse")
    public void cloneDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name,
        @WebParam(name = "sourceName", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String sourceName,
        @WebParam(name = "enabled", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        Boolean enabled)
        throws ManageFault
    ;

    /**
     * 
     * @param nameOfOfflineDataDomain
     * @param enabled
     * @param name
     * @param ddProfileName
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "importDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ImportDataDomain")
    @ResponseWrapper(localName = "importDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ImportDataDomainResponse")
    public void importDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name,
        @WebParam(name = "nameOfOfflineDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String nameOfOfflineDataDomain,
        @WebParam(name = "ddProfileName", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String ddProfileName,
        @WebParam(name = "enabled", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        Boolean enabled)
        throws ManageFault
    ;

    /**
     * 
     * @param nameOfOfflineDataDomain
     * @param name
     * @return
     *     returns java.lang.String
     * @throws ManageFault
     */
    @WebMethod
    @WebResult(name = "exportName", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
    @RequestWrapper(localName = "exportDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ExportDataDomain")
    @ResponseWrapper(localName = "exportDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ExportDataDomainResponse")
    public String exportDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name,
        @WebParam(name = "nameOfOfflineDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String nameOfOfflineDataDomain)
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.DeleteDataDomain")
    @ResponseWrapper(localName = "deleteDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.DeleteDataDomainResponse")
    public void deleteDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name)
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "enableDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.EnableDataDomain")
    @ResponseWrapper(localName = "enableDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.EnableDataDomainResponse")
    public void enableDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name)
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "disableDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.DisableDataDomain")
    @ResponseWrapper(localName = "disableDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.DisableDataDomainResponse")
    public void disableDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name)
        throws ManageFault
    ;

    /**
     * 
     * @param numFollowers
     * @param name
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "rescaleDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.RescaleDataDomain")
    @ResponseWrapper(localName = "rescaleDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.RescaleDataDomainResponse")
    public void rescaleDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name,
        @WebParam(name = "numFollowers", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        Integer numFollowers)
        throws ManageFault
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.endeca.endeca_server.types._2._0.DataDomainDetail>
     * @throws ManageFault
     */
    @WebMethod
    @WebResult(name = "dataDomainDetail", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
    @RequestWrapper(localName = "listDataDomains", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ListDataDomains")
    @ResponseWrapper(localName = "listDataDomainsResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.ListDataDomainsResponse")
    public List<DataDomainDetail> listDataDomains()
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @return
     *     returns com.endeca.endeca_server.types._2._0.DataDomainDetail
     * @throws ManageFault
     */
    @WebMethod
    @WebResult(name = "dataDomainDetail", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
    @RequestWrapper(localName = "getDataDomain", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.GetDataDomain")
    @ResponseWrapper(localName = "getDataDomainResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.GetDataDomainResponse")
    public DataDomainDetail getDataDomain(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name)
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @param timeLimitSec
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "warmCache", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.WarmCache")
    @ResponseWrapper(localName = "warmCacheResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.WarmCacheResponse")
    public void warmCache(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name,
        @WebParam(name = "timeLimitSec", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        Integer timeLimitSec)
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @return
     *     returns com.endeca.endeca_server.types._2._0.DataDomainStats
     * @throws ManageFault
     */
    @WebMethod
    @WebResult(name = "dataDomainStats", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
    @RequestWrapper(localName = "getDataDomainStats", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.GetDataDomainStats")
    @ResponseWrapper(localName = "getDataDomainStatsResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.GetDataDomainStatsResponse")
    public DataDomainStats getDataDomainStats(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name)
        throws ManageFault
    ;

    /**
     * 
     * @param name
     * @return
     *     returns com.endeca.endeca_server.types._2._0.BulkLoadInfo
     * @throws ManageFault
     */
    @WebMethod
    @WebResult(name = "bulkLoad", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
    @RequestWrapper(localName = "allocateBulkLoadPort", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.AllocateBulkLoadPort")
    @ResponseWrapper(localName = "allocateBulkLoadPortResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.AllocateBulkLoadPortResponse")
    public BulkLoadInfo allocateBulkLoadPort(
        @WebParam(name = "name", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0")
        String name)
        throws ManageFault
    ;

    /**
     * 
     * @param serverVersion
     * @param dgraphVersion
     * @throws ManageFault
     */
    @WebMethod
    @RequestWrapper(localName = "version", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", className = "com.endeca.endeca_server.manage._2._0.VersionResponse")
    public void version(
        @WebParam(name = "serverVersion", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", mode = WebParam.Mode.OUT)
        Holder<String> serverVersion,
        @WebParam(name = "dgraphVersion", targetNamespace = "http://www.endeca.com/endeca-server/manage/2/0", mode = WebParam.Mode.OUT)
        Holder<List<DgraphVersion>> dgraphVersion)
        throws ManageFault
    ;

}
