
package br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Semantic Config Service: manages Entities and Attributes in the Semantic Layer
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SConfig", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3", wsdlLocation = "http://192.168.3.50:11001/endeca-server/ws/sconfig/cmsp001?wsdl")
public class SConfig
    extends Service
{

    private final static URL SCONFIG_WSDL_LOCATION;
    private final static WebServiceException SCONFIG_EXCEPTION;
    private final static QName SCONFIG_QNAME = new QName("http://www.endeca.com/endeca-server/sconfig/3", "SConfig");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.3.50:11001/endeca-server/ws/sconfig/cmsp001?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCONFIG_WSDL_LOCATION = url;
        SCONFIG_EXCEPTION = e;
    }

    public SConfig() {
        super(__getWsdlLocation(), SCONFIG_QNAME);
    }

    public SConfig(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCONFIG_QNAME);
    }

    public SConfig(URL wsdlLocation) {
        super(wsdlLocation, SCONFIG_QNAME);
    }

    public SConfig(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCONFIG_QNAME);
    }

    public SConfig(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SConfig(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SConfigPort
     */
    @WebEndpoint(name = "SConfigPort")
    public SConfigPort getSConfigPort() {
        return super.getPort(new QName("http://www.endeca.com/endeca-server/sconfig/3", "SConfigPort"), SConfigPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SConfigPort
     */
    @WebEndpoint(name = "SConfigPort")
    public SConfigPort getSConfigPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.endeca.com/endeca-server/sconfig/3", "SConfigPort"), SConfigPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCONFIG_EXCEPTION!= null) {
            throw SCONFIG_EXCEPTION;
        }
        return SCONFIG_WSDL_LOCATION;
    }

}
