
package br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.Collection;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.CollectionAdditionInformation;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.CollectionKey;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.CollectionRecord;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.CollectionUpdate;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.EntityAdditionInformation;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.FilterRule;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.FilterRuleAdditionInformation;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.FilterRuleKey;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.SemanticEntity;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.SemanticEntityKey;
import br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.ValidatedSemanticEntity;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SConfigPort", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3")
@XmlSeeAlso({
    br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.ObjectFactory.class,
    br.com.cds.connecta.framework.connector.endeca.mdex.eql_parser.types.ObjectFactory.class
})
public interface SConfigPort {


    /**
     * 
     * @param outerTransactionId
     * @param language
     * @return
     *     returns java.util.List<com.endeca.endeca_server.sconfig._3._0.ValidatedSemanticEntity>
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "validatedSemanticEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "listEntities", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ListEntities")
    @ResponseWrapper(localName = "listEntitiesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ListEntitiesResponse")
    public List<ValidatedSemanticEntity> listEntities(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @param semanticEntity
     * @return
     *     returns com.endeca.endeca_server.sconfig._3._0.ValidatedSemanticEntity
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "validatedSemanticEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "validateEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ValidateEntity")
    @ResponseWrapper(localName = "validateEntityResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ValidateEntityResponse")
    public ValidatedSemanticEntity validateEntity(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "semanticEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        SemanticEntity semanticEntity)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @param semanticEntity
     * @return
     *     returns java.util.List<com.endeca.endeca_server.sconfig._3._0.ValidatedSemanticEntity>
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "validatedSemanticEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "validateEntities", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ValidateEntities")
    @ResponseWrapper(localName = "validateEntitiesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ValidateEntitiesResponse")
    public List<ValidatedSemanticEntity> validateEntities(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "semanticEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<SemanticEntity> semanticEntity)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @param semanticEntity
     * @return
     *     returns com.endeca.endeca_server.sconfig._3._0.EntityAdditionInformation
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "entityAdditionInformation", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "putEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutEntity")
    @ResponseWrapper(localName = "putEntityResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutEntityResponse")
    public EntityAdditionInformation putEntity(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "semanticEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        SemanticEntity semanticEntity)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @param semanticEntity
     * @return
     *     returns com.endeca.endeca_server.sconfig._3._0.EntityAdditionInformation
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "entityAdditionInformation", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "putEntities", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutEntities")
    @ResponseWrapper(localName = "putEntitiesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutEntitiesResponse")
    public EntityAdditionInformation putEntities(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "semanticEntity", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<SemanticEntity> semanticEntity)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @return
     *     returns int
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "numEntitiesDeleted", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "deleteAllEntities", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteAllEntities")
    @ResponseWrapper(localName = "deleteAllEntitiesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteAllEntitiesResponse")
    public int deleteAllEntities(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param semanticEntityKey
     * @param language
     * @return
     *     returns int
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "numEntitiesDeleted", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "deleteEntities", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteEntities")
    @ResponseWrapper(localName = "deleteEntitiesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteEntitiesResponse")
    public int deleteEntities(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "semanticEntityKey", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<SemanticEntityKey> semanticEntityKey)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @return
     *     returns java.util.List<com.endeca.endeca_server.sconfig._3._0.CollectionRecord>
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "collectionRecord", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "listCollections", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ListCollections")
    @ResponseWrapper(localName = "listCollectionsResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ListCollectionsResponse")
    public List<CollectionRecord> listCollections(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param collection
     * @param language
     * @return
     *     returns com.endeca.endeca_server.sconfig._3._0.CollectionAdditionInformation
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "collectionAdditionInformation", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "putCollection", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutCollection")
    @ResponseWrapper(localName = "putCollectionResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutCollectionResponse")
    public CollectionAdditionInformation putCollection(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "collection", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        Collection collection)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param collection
     * @param language
     * @return
     *     returns com.endeca.endeca_server.sconfig._3._0.CollectionAdditionInformation
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "collectionAdditionInformation", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "putCollections", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutCollections")
    @ResponseWrapper(localName = "putCollectionsResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutCollectionsResponse")
    public CollectionAdditionInformation putCollections(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "collection", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<Collection> collection)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param collectionUpdate
     * @param language
     * @return
     *     returns int
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "numCollectionsUpdated", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "updateCollections", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.UpdateCollections")
    @ResponseWrapper(localName = "updateCollectionsResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.UpdateCollectionsResponse")
    public int updateCollections(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "collectionUpdate", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<CollectionUpdate> collectionUpdate)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @return
     *     returns int
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "numCollectionsDeleted", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "deleteAllCollections", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteAllCollections")
    @ResponseWrapper(localName = "deleteAllCollectionsResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteAllCollectionsResponse")
    public int deleteAllCollections(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param collectionKey
     * @param language
     * @return
     *     returns int
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "numCollectionsDeleted", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "deleteCollections", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteCollections")
    @ResponseWrapper(localName = "deleteCollectionsResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteCollectionsResponse")
    public int deleteCollections(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "collectionKey", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<CollectionKey> collectionKey)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @return
     *     returns java.util.List<com.endeca.endeca_server.sconfig._3._0.FilterRule>
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "filterRule", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "listFilterRules", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ListFilterRules")
    @ResponseWrapper(localName = "listFilterRulesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.ListFilterRulesResponse")
    public List<FilterRule> listFilterRules(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @param filterRule
     * @return
     *     returns com.endeca.endeca_server.sconfig._3._0.FilterRuleAdditionInformation
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "filterRuleAdditionInformation", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "putFilterRule", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutFilterRule")
    @ResponseWrapper(localName = "putFilterRuleResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutFilterRuleResponse")
    public FilterRuleAdditionInformation putFilterRule(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "filterRule", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        FilterRule filterRule)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @param filterRule
     * @return
     *     returns com.endeca.endeca_server.sconfig._3._0.FilterRuleAdditionInformation
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "filterRuleAdditionInformation", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "putFilterRules", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutFilterRules")
    @ResponseWrapper(localName = "putFilterRulesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.PutFilterRulesResponse")
    public FilterRuleAdditionInformation putFilterRules(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "filterRule", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<FilterRule> filterRule)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param language
     * @return
     *     returns int
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "numFilterRulesDeleted", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "deleteAllFilterRules", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteAllFilterRules")
    @ResponseWrapper(localName = "deleteAllFilterRulesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteAllFilterRulesResponse")
    public int deleteAllFilterRules(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language)
        throws SConfigFault
    ;

    /**
     * 
     * @param outerTransactionId
     * @param filterRuleKey
     * @param language
     * @return
     *     returns int
     * @throws SConfigFault
     */
    @WebMethod
    @WebResult(name = "numFilterRulesDeleted", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
    @RequestWrapper(localName = "deleteFilterRules", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteFilterRules")
    @ResponseWrapper(localName = "deleteFilterRulesResponse", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0", className = "com.endeca.endeca_server.sconfig._3._0.DeleteFilterRulesResponse")
    public int deleteFilterRules(
        @WebParam(name = "outerTransactionId", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String outerTransactionId,
        @WebParam(name = "language", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        String language,
        @WebParam(name = "filterRuleKey", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
        List<FilterRuleKey> filterRuleKey)
        throws SConfigFault
    ;

}
