
package br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SConfigFault", targetNamespace = "http://www.endeca.com/endeca-server/sconfig/3/0")
public class SConfigFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    //private com.endeca.endeca_server.sconfig._3._0.SConfigFault faultInfo;
    private br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.SConfigFault faultInfo;
     
    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SConfigFault(String message, br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.SConfigFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SConfigFault(String message, br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.SConfigFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.endeca.endeca_server.sconfig._3._0.SConfigFault
     */
    public br.com.cds.connecta.framework.connector.endeca.endeca_server.sconfig._3._0.SConfigFault getFaultInfo() {
        return faultInfo;
    }

}
