
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "IBotService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class IBotService
    extends Service
{

    private final static URL IBOTSERVICE_WSDL_LOCATION;
    private final static WebServiceException IBOTSERVICE_EXCEPTION;
    private final static QName IBOTSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "IBotService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IBOTSERVICE_WSDL_LOCATION = url;
        IBOTSERVICE_EXCEPTION = e;
    }

    public IBotService() {
        super(__getWsdlLocation(), IBOTSERVICE_QNAME);
    }

    public IBotService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IBotServiceSoap
     */
    @WebEndpoint(name = "IBotServiceSoap")
    public IBotServiceSoap getIBotServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "IBotServiceSoap"), IBotServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (IBOTSERVICE_EXCEPTION!= null) {
            throw IBOTSERVICE_EXCEPTION;
        }
        return IBOTSERVICE_WSDL_LOCATION;
    }

}
