
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "JobManagementService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class JobManagementService
    extends Service
{

    private final static URL JOBMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOBMANAGEMENTSERVICE_EXCEPTION;
    private final static QName JOBMANAGEMENTSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "JobManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOBMANAGEMENTSERVICE_WSDL_LOCATION = url;
        JOBMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public JobManagementService() {
        super(__getWsdlLocation(), JOBMANAGEMENTSERVICE_QNAME);
    }

    public JobManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns JobManagementServiceSoap
     */
    @WebEndpoint(name = "JobManagementServiceSoap")
    public JobManagementServiceSoap getJobManagementServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "JobManagementServiceSoap"), JobManagementServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (JOBMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw JOBMANAGEMENTSERVICE_EXCEPTION;
        }
        return JOBMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
