
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "MetadataService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class MetadataService
    extends Service
{

    private final static URL METADATASERVICE_WSDL_LOCATION;
    private final static WebServiceException METADATASERVICE_EXCEPTION;
    private final static QName METADATASERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "MetadataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METADATASERVICE_WSDL_LOCATION = url;
        METADATASERVICE_EXCEPTION = e;
    }

    public MetadataService() {
        super(__getWsdlLocation(), METADATASERVICE_QNAME);
    }

    public MetadataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MetadataServiceSoap
     */
    @WebEndpoint(name = "MetadataServiceSoap")
    public MetadataServiceSoap getMetadataServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "MetadataServiceSoap"), MetadataServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (METADATASERVICE_EXCEPTION!= null) {
            throw METADATASERVICE_EXCEPTION;
        }
        return METADATASERVICE_WSDL_LOCATION;
    }

}
