
package br.com.cds.connecta.framework.connector.obiee;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MetadataServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v6")
public interface MetadataServiceSoap {


    /**
     * 
     * @param sessionID
     * @return
     *     returns boolean
     */
    @WebMethod(action = "#clearQueryCache")
    @WebResult(name = "result", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "clearQueryCache", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ClearQueryCache")
    @ResponseWrapper(localName = "clearQueryCacheResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ClearQueryCacheResult")
    public boolean clearQueryCache(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns java.util.List<oracle.bi.web.soap.SASubjectArea>
     */
    @WebMethod(action = "#getSubjectAreas")
    @WebResult(name = "subjectArea", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "getSubjectAreas", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetSubjectAreas")
    @ResponseWrapper(localName = "getSubjectAreasResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GetSubjectAreasResult")
    public List<SASubjectArea> getSubjectAreas(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param subjectAreaName
     * @param sessionID
     * @param detailsLevel
     * @return
     *     returns oracle.bi.web.soap.SASubjectArea
     */
    @WebMethod(action = "#describeSubjectArea")
    @WebResult(name = "subjectArea", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "describeSubjectArea", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.DescribeSubjectArea")
    @ResponseWrapper(localName = "describeSubjectAreaResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.DescribeSubjectAreaResult")
    public SASubjectArea describeSubjectArea(
        @WebParam(name = "subjectAreaName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String subjectAreaName,
        @WebParam(name = "detailsLevel", targetNamespace = "urn://oracle.bi.webservices/v6")
        SASubjectAreaDetails detailsLevel,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param subjectAreaName
     * @param sessionID
     * @param tableName
     * @param detailsLevel
     * @return
     *     returns oracle.bi.web.soap.SATable
     */
    @WebMethod(action = "#describeTable")
    @WebResult(name = "table", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "describeTable", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.DescribeTable")
    @ResponseWrapper(localName = "describeTableResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.DescribeTableResult")
    public SATable describeTable(
        @WebParam(name = "subjectAreaName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String subjectAreaName,
        @WebParam(name = "tableName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String tableName,
        @WebParam(name = "detailsLevel", targetNamespace = "urn://oracle.bi.webservices/v6")
        SATableDetails detailsLevel,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param subjectAreaName
     * @param sessionID
     * @param tableName
     * @param columnName
     * @return
     *     returns oracle.bi.web.soap.SAColumn
     */
    @WebMethod(action = "#describeColumn")
    @WebResult(name = "column", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "describeColumn", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.DescribeColumn")
    @ResponseWrapper(localName = "describeColumnResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.DescribeColumnResult")
    public SAColumn describeColumn(
        @WebParam(name = "subjectAreaName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String subjectAreaName,
        @WebParam(name = "tableName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String tableName,
        @WebParam(name = "columnName", targetNamespace = "urn://oracle.bi.webservices/v6")
        String columnName,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

}
