
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ReplicationService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class ReplicationService
    extends Service
{

    private final static URL REPLICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPLICATIONSERVICE_EXCEPTION;
    private final static QName REPLICATIONSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "ReplicationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPLICATIONSERVICE_WSDL_LOCATION = url;
        REPLICATIONSERVICE_EXCEPTION = e;
    }

    public ReplicationService() {
        super(__getWsdlLocation(), REPLICATIONSERVICE_QNAME);
    }

    public ReplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ReplicationServiceSoap
     */
    @WebEndpoint(name = "ReplicationServiceSoap")
    public ReplicationServiceSoap getReplicationServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "ReplicationServiceSoap"), ReplicationServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (REPLICATIONSERVICE_EXCEPTION!= null) {
            throw REPLICATIONSERVICE_EXCEPTION;
        }
        return REPLICATIONSERVICE_WSDL_LOCATION;
    }

}
