
package br.com.cds.connecta.framework.connector.obiee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ReportEditingServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v6")
public interface ReportEditingServiceSoap {


    /**
     * 
     * @param encodeInString
     * @param sessionID
     * @param reportRef
     * @param reportParams
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "#applyReportParams")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "applyReportParams", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ApplyReportParams")
    @ResponseWrapper(localName = "applyReportParamsResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ApplyReportParamsResult")
    public Object applyReportParams(
        @WebParam(name = "reportRef", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportRef reportRef,
        @WebParam(name = "reportParams", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportParams reportParams,
        @WebParam(name = "encodeInString", targetNamespace = "urn://oracle.bi.webservices/v6")
        boolean encodeInString,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param reportRef
     * @param reportParams
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#generateReportSQL")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "generateReportSQL", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GenerateReportSQL")
    @ResponseWrapper(localName = "generateReportSQLResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.GenerateReportSQLResult")
    public String generateReportSQL(
        @WebParam(name = "reportRef", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportRef reportRef,
        @WebParam(name = "reportParams", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportParams reportParams,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param reportRefs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#applyReportDefaults")
    @WebResult(name = "reportXml", targetNamespace = "urn://oracle.bi.webservices/v6")
    @RequestWrapper(localName = "applyReportDefaults", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ApplyReportDefaults")
    @ResponseWrapper(localName = "applyReportDefaultsResult", targetNamespace = "urn://oracle.bi.webservices/v6", className = "oracle.bi.web.soap.ApplyReportDefaultsResult")
    public String applyReportDefaults(
        @WebParam(name = "reportRefs", targetNamespace = "urn://oracle.bi.webservices/v6")
        ReportRef reportRefs,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v6")
        String sessionID);

}
