
package br.com.cds.connecta.framework.connector.obiee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SAWSessionService", targetNamespace = "urn://oracle.bi.webservices/v6", wsdlLocation = "http://bivm1:9704/analytics/saw.dll?WSDL")
public class SAWSessionService
    extends Service
{

    private final static URL SAWSESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAWSESSIONSERVICE_EXCEPTION;
    private final static QName SAWSESSIONSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v6", "SAWSessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bivm1:9704/analytics/saw.dll?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAWSESSIONSERVICE_WSDL_LOCATION = url;
        SAWSESSIONSERVICE_EXCEPTION = e;
    }

    public SAWSessionService() {
        super(__getWsdlLocation(), SAWSESSIONSERVICE_QNAME);
    }
    
    public SAWSessionService(URL wsdlLocation) {
        super(wsdlLocation, SAWSESSIONSERVICE_QNAME);
    }

    public SAWSessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SAWSessionServiceSoap
     */
    @WebEndpoint(name = "SAWSessionServiceSoap")
    public SAWSessionServiceSoap getSAWSessionServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v6", "SAWSessionServiceSoap"), SAWSessionServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (SAWSESSIONSERVICE_EXCEPTION!= null) {
            throw SAWSESSIONSERVICE_EXCEPTION;
        }
        return SAWSESSIONSERVICE_WSDL_LOCATION;
    }

}
